### ISSUE TITLE
apparent `gmse_apply` issue with `ownership_var` in branch `jeroen`

### ISSUE THREAD

**Issue by jejoenje** [ConFooBio/gmse#61]
I can't seem `gmse_apply()` to work with the revisions to the implementation of `ownership var`.
Although the parameter does not throw an error when passed to `gmse_apply`, its effect does not seem to be implemented:

```
### Whereas this works as expected:
test_gmse = gmse(time_max = 2, stakeholders = 8, land_ownership = TRUE, ownership_var = 0.5)
table(test_gmse$land[[1]][,,3])

### This, does not:
test = gmse_apply(get_res = "Full", stakeholders = 8, land_ownership = TRUE, ownership_var = 0.5)
table(test$LAND[,,3])
```

I am not sure but may be `pass_paras()` in [`gmse_apply.R`](https://github.com/ConFooBio/gmse/blob/jeroen/R/gmse_apply.R) does not include `ownership_var` yet - I must admit I don't quite understand the `paras` vector in that function, however...?

**Comment by bradduthie** [comment]
Okay, I've edited the `gmse_apply` function in [the commit bb0cd910fe5ded0ec431ef805c4e4dafd0f1ccef](https://github.com/ConFooBio/gmse/commit/bb0cd910fe5ded0ec431ef805c4e4dafd0f1ccef). I think that [this line](https://github.com/ConFooBio/gmse/commit/bb0cd910fe5ded0ec431ef805c4e4dafd0f1ccef#diff-d4d6aa81029a2ee222d140bec2086e21R1389) was the hang up. The HEAD now should be working fine with no errors, warnings, or notes. And the landscape appears to do what it is supposed to with `ownership_var`. The issue appeared to be in the `collect_land_ini` now on [L1357](https://github.com/ConFooBio/gmse/blob/bb0cd910fe5ded0ec431ef805c4e4dafd0f1ccef/R/gmse_apply.R#L1357). The `paras` vector actually doesn't need the `ownership_var` information (weird, but this is because the landscape is made outside of any of the subfunctions that rely on `paras`).

I removed some of the commented sections and reverted the code -- the two above functions you posted now give identical cell ownership for me. Do you still get an error with `gmse_apply` though? If so, can you reproduce on the head of this branch?

**Comment by jejoenje** [comment]
Spot on @bradduthie ! Thank you. I was looking for the issue much higher up in `gmse_apply.R` and never twigged that `ownership_var` would be needed by functions further down, too.

This all works now, from my end - would you like me to try to merge to `rev`?

Incidentally,  what does the function `collect_itb_ini()` do, purely out of interest?

**Comment by jejoenje** [comment]
MMh let's hold fire, I am now managing to crash R and RStudio when trying to run GMSE with the new revisions in my extended "scenario" sets; it seems to work absolutely fine when I put parameters into `gmse_apply` directly but not when adding from pre-existing variables (just for convenience when looping multiple simulations/scenarios). Weird??

I'll do some more tests, and will report back.

I've currently got the revisions running as a locally compiled/installed package though, so I'm wondering whether it is that (i.e. some local issue) - I can't seem to get `install_github("ConFooBio/gmse", ref = "jeroen")` to work, I assume that it is because of repo settings only allowing remote installation from specific branches?

**Comment by jejoenje** [comment]
Yes I **think** this is just a local problem with me compiling/installing a locally installed branch (`jeroen`) - for some reason using input variable names that are identical to `gmse_apply` argument names crashes things in this case; so this
```
gmse_apply(get_res = "Full", land_dim_1 = land_dim_1, land_dim_2 = land_dim_2, ...
```
etc. doesn't work when I've locally compiled and installed branch `jeroen`, whereas it DOES when I am working from either `rev` or `dev` installed remotely from Github.
Given that I can't imagine any of the changes made to `jeroen` would have caused this sort of an issue, I can only assume that the issue purely is with local compiles/installs...?
I can seem to remotely install `jeroen` (`install_github("ConFooBio/gmse", ref = "jeroen")`, - I assume this is due to repo settings? - so I can confirm when we have merged `jeroen` into `rev`.

**Comment by bradduthie** [comment]
Huh, @jejoenje -- okay, let's make sure that this is truly a local issue. Can you send me a script to try to replicate the crash? Also, what version of R are you currently running? I'm still on v3.6.3. 

It just occurred to me that there was a difference in an earlier script you sent. Let me find the line to see if I can diagnose.

**Comment by bradduthie** [comment]
Could [this line](https://github.com/ConFooBio/gmse/blob/92a1a34d27544bd91303fa39cab2c70c1615c654/R/gmse_apply.R#L1234) and the edit above it be an issue? I reverted it back because I think that you need the `eval` there?

Oh, sorry, to answer your question, `collect_itb_ini`, I think, collects the arguments for constructing an array of interactions between the land and resources (just a two by two array at the moment, used [here in `gmse`](https://github.com/ConFooBio/gmse/blob/14fa66a0b3bcd2a2d8cf8a7c4bb6b8a0ec404e2e/R/gmse.R#L212), but to potentially be expanded if there ever are more resource types or landscape layers). The function first assumes the GMSE defaults, then checks to see if any non-defaults should replace these instead (e.g., due to specification in `gmse_apply` or an old list). It's a bit maddening in the end, since the `gmse_apply` code has to have all of these kinds of checks and updates for building the key structures -- using GMSE defaults when it must but updating with specified values whenever they are provided. All of the `eval`, `formals`, `do.call` functions etc. are things that I had never really used much if at all before writing `gmse_apply`.

**Comment by jejoenje** [comment]
> Could this line and the edit above it be an issue? I reverted it back because I think that you need the eval there?
It could be, I was looking for that edit/commit earlier and I couldn't for the life of me find it.
But that line should be the same between `rev` and `jeroen` right?

I now don't seem to be able to reproduce my own issue... ARGH!
Bear with me, it might just be best if I send you a script for you to try in your own installation of `jeroen`...

**Comment by jejoenje** [comment]
> Hold @jejoenje -- I just noticed that collect_itb_ini actually needs to be fixed in gmse_apply. I'm going to do this and push to 'jeroen' (unless you'd prefer I push to a different new branch)?

No go for it - please do.

OK I think I have definitely confirmed this was just a local issue, so I think we can stop worrying about this - I believe it was being caused by me using a menu option in RStudio to install and build a local package (as opposed to using `devtools::install(reload = TRUE, quick = FALSE, build = TRUE)`. The only thing I can think is that for some reason it was causing difficulties with local package installs (I can't quite work out why but I suspect that RStudio dropdown option isn't using some key settings?). Anyway, it seems to be working as expected now, but I'll email you a script separately.

**Comment by bradduthie** [comment]
Okay, thanks @jejoenje -- will tag you once I've got `gmse_apply` working correctly again.
